Repository yanJuicy/jeju-iiin, pull requests merged in 2022-12, with the labels that each got.

#2 ✨ feat: 초기 프로젝트 구조 설정
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/jejuiiin/JejuIiinApplication.java
  src/main/java/com/example/jejuiiin/controller/EmptyController.java
  src/main/java/com/example/jejuiiin/domain/Cart.java
  src/main/java/com/example/jejuiiin/domain/CartItem.java
  src/main/java/com/example/jejuiiin/domain/Member.java
  src/main/java/com/example/jejuiiin/domain/Product.java
  src/main/java/com/example/jejuiiin/domain/Review.java
  src/main/java/com/example/jejuiiin/domain/SocialType.java
  src/main/java/com/example/jejuiiin/domain/TimeStamped.java
  src/main/java/com/example/jejuiiin/repository/CartItemRepository.java
  src/main/java/com/example/jejuiiin/repository/CartRepository.java
  src/main/java/com/example/jejuiiin/repository/MemberRepository.java
  src/main/java/com/example/jejuiiin/repository/ProductRepository.java
  src/main/java/com/example/jejuiiin/repository/ReviewRepository.java
  src/main/java/com/example/jejuiiin/service/EmptyService.java
  src/main/resources/application.properties
  src/test/java/com/example/jejuiiin/JejuIiinApplicationTests.java
Labels: enhancement

#5 ✨ feat: Controller, Service 공통 파일 생성
  src/main/java/com/example/jejuiiin/controller/CartController.java
  src/main/java/com/example/jejuiiin/controller/CartItemController.java
  src/main/java/com/example/jejuiiin/controller/EmptyController.java
  src/main/java/com/example/jejuiiin/controller/MemberController.java
  src/main/java/com/example/jejuiiin/controller/ProductController.java
  src/main/java/com/example/jejuiiin/controller/ReviewController.java
  src/main/java/com/example/jejuiiin/service/CartService.java
  src/main/java/com/example/jejuiiin/service/EmptyService.java
  src/main/java/com/example/jejuiiin/service/MemberService.java
  src/main/java/com/example/jejuiiin/service/ProductService.java
  src/main/java/com/example/jejuiiin/service/ReviewService.java
Labels: enhancement

#12 ✨ Feat: RDS mysql 연결 설정
  .gitignore
  build.gradle
  src/main/resources/application.properties
Labels: envirionment

#13 🔧 Chore: CI 스크립트 작성
  .github/workflows/gradle.yml
Labels: envirionment

#20 ♻️ Refactor: Product 엔터티 카테고리 필드 추가
  src/main/java/com/example/jejuiiin/domain/Product.java
  src/main/java/com/example/jejuiiin/domain/ProductCategory.java
  src/main/java/com/example/jejuiiin/domain/ProductSubCategory.java
Labels: refactor

#24 ✨feat - 상세 페이지 조회 기능 추가
  build.gradle
  src/main/java/com/example/jejuiiin/controller/ProductController.java
  src/main/java/com/example/jejuiiin/mapper/ProductDetailResponse.java
  src/main/java/com/example/jejuiiin/mapper/ProductMapper.java
  src/main/java/com/example/jejuiiin/service/ProductService.java
Labels: enhancement

#26 ✨ Feat: CORS 설정 클래스 작성
  src/main/java/com/example/jejuiiin/config/WebConfig.java
Labels: enhancement

#27 ♻️ Refactor: Cart, CartItem 엔터티 합치기
  src/main/java/com/example/jejuiiin/controller/CartItemController.java
  src/main/java/com/example/jejuiiin/domain/Cart.java
  src/main/java/com/example/jejuiiin/domain/CartItem.java
  src/main/java/com/example/jejuiiin/domain/Product.java
  src/main/java/com/example/jejuiiin/repository/CartItemRepository.java
Labels: refactor

#30 ✨ Feat: CD 스크립트 작성
  .github/workflows/gradle.yml
  appspec.yml
  scripts/start.sh
  scripts/stop.sh
  src/main/resources/application.properties
Labels: envirionment

#14 ✨ Feat: Spring Security 추가
  .gitignore
  build.gradle
  src/main/java/com/example/jejuiiin/controller/response/Response.java
  src/main/java/com/example/jejuiiin/exception/ExceptionMessage.java
  src/main/java/com/example/jejuiiin/repository/MemberRepository.java
  src/main/java/com/example/jejuiiin/security/UserDetailsImpl.java
  src/main/java/com/example/jejuiiin/security/UserDetailsServiceImpl.java
  src/main/java/com/example/jejuiiin/security/WebSecurityConfig.java
  src/main/java/com/example/jejuiiin/security/jwt/JwtAuthFilter.java
  src/main/java/com/example/jejuiiin/security/jwt/JwtUtil.java
  src/main/java/com/example/jejuiiin/security/jwt/exception/CustomSecurityException.java
  src/main/java/com/example/jejuiiin/security/jwt/exception/JwtExceptionHandlerFilter.java
Labels: enhancement, envirionment

#32 ♻️ refactor: Security url 전체 허용
  src/main/java/com/example/jejuiiin/security/WebSecurityConfig.java
Labels: envirionment

#33 ♻️ refactor: Token 없을 경우 요청 통과 하도록 설정
  src/main/java/com/example/jejuiiin/security/jwt/JwtAuthFilter.java
Labels: envirionment

#36 ✨ Feat: 카테고리별 상품 조회
  build.gradle
  src/main/generated/com/example/jejuiiin/mapper/ProductMapperMapStructImpl.java
  src/main/java/com/example/jejuiiin/controller/ProductController.java
  src/main/java/com/example/jejuiiin/controller/handler/GlobalExceptionHandler.java
  src/main/java/com/example/jejuiiin/controller/request/FindCategoryProductRequest.java
  src/main/java/com/example/jejuiiin/controller/response/CategoryProductResponse.java
  src/main/java/com/example/jejuiiin/controller/response/PageResponse.java
  src/main/java/com/example/jejuiiin/controller/response/Response.java
  src/main/java/com/example/jejuiiin/controller/response/message/SuccessMessage.java
  src/main/java/com/example/jejuiiin/exception/ExceptionMessage.java
  src/main/java/com/example/jejuiiin/mapper/ProductMapperMapStruct.java
  src/main/java/com/example/jejuiiin/repository/ProductRepository.java
  src/main/java/com/example/jejuiiin/service/ProductService.java
Labels: enhancement

#39 ✨ Feat: React APP CORS 허용
  src/main/java/com/example/jejuiiin/config/WebConfig.java
Labels: enhancement

#37 ✨ Feat: 서브 카테고리별 상품 조회
  .gitignore
  src/main/generated/com/example/jejuiiin/mapper/ProductMapperMapStructImpl.java
  src/main/java/com/example/jejuiiin/controller/ProductController.java
  src/main/java/com/example/jejuiiin/controller/request/FindCategoryProductRequest.java
  src/main/java/com/example/jejuiiin/repository/ProductRepository.java
  src/main/java/com/example/jejuiiin/service/ProductService.java
Labels: enhancement

#43 📝 Doc: PR 템플릿에 스크린샷 내용 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: envirionment

#46 ♻️ Refactor: exception 패키지 이동
  src/main/java/com/example/jejuiiin/controller/exception/ExceptionMessage.java
  src/main/java/com/example/jejuiiin/controller/handler/GlobalExceptionHandler.java
  src/main/java/com/example/jejuiiin/controller/response/Response.java
  src/main/java/com/example/jejuiiin/security/jwt/JwtAuthFilter.java
  src/main/java/com/example/jejuiiin/security/jwt/JwtUtil.java
  src/main/java/com/example/jejuiiin/security/jwt/exception/CustomSecurityException.java
Labels: refactor

#48 ♻️Refactor: 신규상품조회 상태코드 메시지 추가 및 조회 개수 5개->4개 수정
  src/main/java/com/example/jejuiiin/controller/ProductController.java
  src/main/java/com/example/jejuiiin/repository/ProductRepository.java
  src/main/java/com/example/jejuiiin/service/ProductService.java
Labels: refactor

#49 ♻️ Refactor - 상세 페이지 조회 응답 포맷 변경
  src/main/java/com/example/jejuiiin/controller/ProductController.java
Labels: refactor

#53 ✨ feat: 회원가입 API 구현
  build.gradle
  src/main/java/com/example/jejuiiin/controller/MemberController.java
  src/main/java/com/example/jejuiiin/controller/exception/DuplicateEmailException.java
  src/main/java/com/example/jejuiiin/controller/exception/DuplicateException.java
  src/main/java/com/example/jejuiiin/controller/exception/DuplicateLoginIdException.java
  src/main/java/com/example/jejuiiin/controller/exception/ExceptionMessage.java
  src/main/java/com/example/jejuiiin/controller/handler/GlobalExceptionHandler.java
  src/main/java/com/example/jejuiiin/controller/request/SignupRequest.java
  src/main/java/com/example/jejuiiin/controller/request/SignupServiceRequest.java
  src/main/java/com/example/jejuiiin/mapper/MemberMapper.java
  src/main/java/com/example/jejuiiin/repository/MemberRepository.java
  src/main/java/com/example/jejuiiin/service/MemberService.java
Labels: enhancement

#57 ♻️ Refactor: Cart -> CartItem으로 엔터티 이름 변경
  src/main/java/com/example/jejuiiin/domain/Cart.java
  src/main/java/com/example/jejuiiin/domain/CartItem.java
  src/main/java/com/example/jejuiiin/repository/CartRepository.java
Labels: refactor

#56 ✨ 로그인 API 구현
  src/main/java/com/example/jejuiiin/controller/MemberController.java
  src/main/java/com/example/jejuiiin/controller/exception/ExceptionMessage.java
  src/main/java/com/example/jejuiiin/controller/request/LoginRequest.java
  src/main/java/com/example/jejuiiin/controller/request/LoginServiceRequest.java
  src/main/java/com/example/jejuiiin/mapper/MemberMapper.java
  src/main/java/com/example/jejuiiin/security/jwt/JwtUtil.java
  src/main/java/com/example/jejuiiin/service/MemberService.java
Labels: enhancement

#59 ♻️Refactor: (썸네일 사이즈)thumbnail_img_url 로 통일
  src/main/java/com/example/jejuiiin/controller/response/CategoryProductResponse.java
  src/main/java/com/example/jejuiiin/controller/response/ProductResponse.java
  src/main/java/com/example/jejuiiin/domain/Product.java
  src/main/java/com/example/jejuiiin/mapper/ProductDetailResponse.java
  src/main/java/com/example/jejuiiin/mapper/ProductMapper.java
Labels: refactor

#61 🐛 회원가입, 로그인 시 오류 해결
  src/main/java/com/example/jejuiiin/controller/request/LoginRequest.java
  src/main/java/com/example/jejuiiin/controller/request/LoginServiceRequest.java
  src/main/java/com/example/jejuiiin/controller/request/SignupRequest.java
  src/main/java/com/example/jejuiiin/controller/request/SignupServiceRequest.java
  src/main/java/com/example/jejuiiin/service/MemberService.java
Labels: bug

#62 ✨ Feat: 장바구니에 상품 넣기 API
  src/main/java/com/example/jejuiiin/controller/CartController.java
  src/main/java/com/example/jejuiiin/controller/exception/ExceptionMessage.java
  src/main/java/com/example/jejuiiin/controller/handler/GlobalExceptionHandler.java
  src/main/java/com/example/jejuiiin/controller/request/CreateCartItemRequest.java
  src/main/java/com/example/jejuiiin/controller/response/CreateCartItemResponse.java
  src/main/java/com/example/jejuiiin/domain/CartItem.java
  src/main/java/com/example/jejuiiin/repository/CartRepository.java
  src/main/java/com/example/jejuiiin/service/CartService.java
Labels: enhancement

#64 ✨ Feat: 카테고리별 상품 조회 응답 데이터 추가
  src/main/java/com/example/jejuiiin/controller/ProductController.java
  src/main/java/com/example/jejuiiin/controller/response/CategoryProductPageResponse.java
  src/main/java/com/example/jejuiiin/controller/response/CategoryProductResponseData.java
  src/main/java/com/example/jejuiiin/controller/response/PageResponse.java
  src/main/java/com/example/jejuiiin/controller/response/message/SuccessMessage.java
  src/main/java/com/example/jejuiiin/mapper/ProductMapperMapStruct.java
  src/main/java/com/example/jejuiiin/service/ProductService.java
Labels: enhancement

#66 ✨ Feat: 재주상회 크롤링
  python/jeju_iiin_crawling.py
Labels: enhancement

#69 ✨ 헤더에 필요한 정보 반환 API 구현
  src/main/java/com/example/jejuiiin/controller/HeaderController.java
  src/main/java/com/example/jejuiiin/controller/response/HeaderResponse.java
  src/main/java/com/example/jejuiiin/repository/CartItemRepository.java
  src/main/java/com/example/jejuiiin/service/CartService.java
  src/main/java/com/example/jejuiiin/service/HeaderService.java
Labels: enhancement

#72 ✨ Feat: 장바구니 내 선택 상품 수량 변경
  src/main/java/com/example/jejuiiin/controller/CartController.java
  src/main/java/com/example/jejuiiin/controller/exception/ExceptionMessage.java
  src/main/java/com/example/jejuiiin/controller/handler/GlobalExceptionHandler.java
  src/main/java/com/example/jejuiiin/controller/request/CartItemRequest.java
  src/main/java/com/example/jejuiiin/controller/request/CartItemServiceRequest.java
  src/main/java/com/example/jejuiiin/controller/response/CartItemResponse.java
  src/main/java/com/example/jejuiiin/domain/CartItem.java
  src/main/java/com/example/jejuiiin/repository/CartRepository.java
  src/main/java/com/example/jejuiiin/service/CartService.java
  src/main/java/com/example/jejuiiin/service/HeaderService.java
Labels: enhancement

#74 ♻️ Refactor: Cart 도메인 리팩터링
  src/main/java/com/example/jejuiiin/controller/CartController.java
  src/main/java/com/example/jejuiiin/mapper/CartMapper.java
  src/main/java/com/example/jejuiiin/service/CartService.java
Labels: refactor

#73 ♻️ Security 예외 처리 로직 수정
  src/main/java/com/example/jejuiiin/controller/HeaderController.java
  src/main/java/com/example/jejuiiin/controller/exception/ExceptionMessage.java
  src/main/java/com/example/jejuiiin/security/jwt/JwtAuthFilter.java
  src/main/java/com/example/jejuiiin/security/jwt/JwtUtil.java
  src/main/java/com/example/jejuiiin/security/jwt/exception/JwtExceptionHandlerFilter.java
Labels: refactor

#81 ✨feat: 장바구니 조회 API
  src/main/java/com/example/jejuiiin/controller/CartController.java
  src/main/java/com/example/jejuiiin/controller/response/MyCartResponse.java
  src/main/java/com/example/jejuiiin/repository/CartRepository.java
  src/main/java/com/example/jejuiiin/service/CartService.java
Labels: enhancement

#83 ✨ Feat: 깃허브 로그인
  .gitignore
  src/main/java/com/example/jejuiiin/controller/OAuth2Controller.java
  src/main/java/com/example/jejuiiin/controller/exception/ExceptionMessage.java
  src/main/java/com/example/jejuiiin/controller/exception/OAuth2LoginException.java
  src/main/java/com/example/jejuiiin/controller/handler/GlobalExceptionHandler.java
  src/main/java/com/example/jejuiiin/controller/request/GithubLoginRequest.java
  src/main/java/com/example/jejuiiin/service/GithubService.java
  src/main/java/com/example/jejuiiin/service/vo/GithubUserInfo.java
  src/main/resources/application.properties
Labels: enhancement

#84 ♻️ Refactor: 장바구니 상품 수량 변경 API 응답 DTO 변경
  src/main/java/com/example/jejuiiin/controller/response/MyCartResponse.java
  src/main/java/com/example/jejuiiin/mapper/CartMapper.java
  src/main/java/com/example/jejuiiin/service/CartService.java
Labels: refactor

#85 ✨feat: 장바구니 삭제 API
  src/main/java/com/example/jejuiiin/controller/CartController.java
  src/main/java/com/example/jejuiiin/controller/request/DeleteCartItemRequest.java
  src/main/java/com/example/jejuiiin/service/CartService.java
Labels: enhancement

#90 ♻️ Refactor: Github와 통신할 때 발생하는 예외 처리
  src/main/java/com/example/jejuiiin/controller/handler/GlobalExceptionHandler.java
  src/main/java/com/example/jejuiiin/service/GithubService.java
Labels: refactor

#91 ✨ feat: Order 엔티티와 OrderRepository 추가
  src/main/java/com/example/jejuiiin/domain/Order.java
  src/main/java/com/example/jejuiiin/repository/OrderRepository.java
Labels: enhancement

#93 ♻️ Refactor: WebSecurityConfig 리팩터링
  src/main/java/com/example/jejuiiin/config/WebConfig.java
  src/main/java/com/example/jejuiiin/config/WebSecurityConfig.java
Labels: refactor

#95 ♻️ Refactor: 장바구니 삭제 api ( 잔여 장바구니 데이터 반환 )
  src/main/java/com/example/jejuiiin/controller/CartController.java
Labels: refactor

#101 🐛 Fix: 만료된 토큰으로 로그인 API 요청 시 예외 처리 제외
  src/main/java/com/example/jejuiiin/security/jwt/exception/JwtExceptionHandlerFilter.java
Labels: bug, enhancement

#97 ✨ Feat: 카카오 로그인 회원가입 기능 추가
  build.gradle
  src/main/java/com/example/jejuiiin/config/PropertyEncryptConfig.java
  src/main/java/com/example/jejuiiin/controller/OAuth2Controller.java
  src/main/java/com/example/jejuiiin/controller/response/SocialMemberInfo.java
  src/main/java/com/example/jejuiiin/domain/Member.java
  src/main/java/com/example/jejuiiin/service/KakaoService.java
Labels: enhancement

#102 🔧 Chore: gradle 캐싱 기능 설정
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
Labels: envirionment

#100 ✨ feat: 상품 주문 API 구현
  src/main/java/com/example/jejuiiin/JejuIiinApplication.java
  src/main/java/com/example/jejuiiin/controller/OrderController.java
  src/main/java/com/example/jejuiiin/controller/exception/ExceptionMessage.java
  src/main/java/com/example/jejuiiin/controller/request/OrderItem.java
  src/main/java/com/example/jejuiiin/controller/request/OrderRequest.java
  src/main/java/com/example/jejuiiin/controller/request/OrderSave.java
  src/main/java/com/example/jejuiiin/controller/response/OrderHistoryResponse.java
  src/main/java/com/example/jejuiiin/domain/Order.java
  src/main/java/com/example/jejuiiin/mapper/OrderMapper.java
  src/main/java/com/example/jejuiiin/repository/OrderRepository.java
  src/main/java/com/example/jejuiiin/service/CartService.java
  src/main/java/com/example/jejuiiin/service/OrderService.java
  src/main/java/com/example/jejuiiin/service/util/ServiceUtil.java
Labels: enhancement

#106 ✨ Feat: API 시간 측정
  src/main/java/com/example/jejuiiin/aop/TimeAop.java
Labels: enhancement

#105 ♻️ Refactor : 카카오로그인 GET 방식을 POST로 변경
  src/main/java/com/example/jejuiiin/controller/OAuth2Controller.java
Labels: refactor

#110 ♻️Refactor: 장바구니 상품 삭제하게 / 다중 선택 삭제
  src/main/java/com/example/jejuiiin/controller/CartController.java
  src/main/java/com/example/jejuiiin/controller/request/DeleteCartItemRequest.java
  src/main/java/com/example/jejuiiin/service/CartService.java
Labels: refactor

#111 ✨ Feat: Crawling 용 Flask 서버 배포
  python/app.py
  python/config.json
  python/jeju_iiin_crawling.py
Labels: enhancement

#117 🧪 Test: 장바구니 100개 데이터를 생성하는 테스트 코드 작성
  src/test/java/com/example/jejuiiin/domain/CartItemTest.java
Labels: test

#115 ♻️ Refactor: Product 도메인 MapStruct 전환
  src/main/java/com/example/jejuiiin/controller/ProductController.java
  src/main/java/com/example/jejuiiin/controller/response/ProductResponse.java
  src/main/java/com/example/jejuiiin/mapper/ProductMapper.java
  src/main/java/com/example/jejuiiin/mapper/ProductMapperMapStruct.java
  src/main/java/com/example/jejuiiin/service/ProductService.java
Labels: refactor

#119 🔧 Chore: 리액트 배포 앱 CORS 설정
  src/main/java/com/example/jejuiiin/config/WebSecurityConfig.java
Labels: refactor

#120 ♻️ refactor: 주문 시 장바구니 삭제 쿼리 변경
  src/main/java/com/example/jejuiiin/controller/OrderController.java
  src/main/java/com/example/jejuiiin/repository/CartRepository.java
  src/main/java/com/example/jejuiiin/service/OrderService.java
Labels: enhancement
